#!/usr/bin/env bash

OPTIONFILE=/etc/X11/Xsession.options
SYSSESSIONDIR=/etc/X11/Xsession.d
SYSRESOURCES=/etc/X11/Xresources

xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto
xrandr --dpi 96
xsetroot -cursor_name left_ptr

# use run-parts to source every file in the session directory; we source
# instead of executing so that the variables and functions defined above
# are available to the scripts, and so that they can pass variables to each
# other
SESSIONFILES=$(run-parts --list $SYSSESSIONDIR)
if [ -n "$SESSIONFILES" ]; then
  set +e
  for SESSIONFILE in $SESSIONFILES; do
    . $SESSIONFILE
  done
  set -e
fi

exit 0